### PR TITLE
Add PowerShell support

### LINKED ISSUE #192: PowerShell Support
Would be a fantastic addition to the supported languages.

### LINKED ISSUE #456: Feature Request: Add New Language - PowerShell (Core?)
Hello, I'd love to see about getting PowerShell as part of Code Wars (even if it has to be PowerShell Core - that runs on Linux / Dockers).

I don't know the first thing about getting a new language added, but once it would be setup, I would love to contribute and our PowerShell User Group here in STL would add to it montly!

Please let me know - or community if any of you can help to get a "shell" of the language setup.  Thanks!!!!

### PR DESCRIPTION
**Pull request by kazk**
@PowerSchill
#477 is failing because it contains merge conflict markers. I decided to rebase instead of asking you to try again because I noticed some things to be fixed anyways.

---

closes #456, closes #192

### CODE REVIEW

**Comment by kazk** [comment]
@jhoffner I'll rebase this again.

**Comment by kenmaglio** [comment]
With this being merged in and now at a Basic Run level in the project what are the next steps ?

**Comment by kazk** [comment]
@kenmaglio We have testing support thanks to @PowerSchill. Next, we'll add the language to Codewars as beta and see how it goes. I can't give you any timelines yet.

**Comment by kenmaglio** [comment]
@PowerSchill work was great. I didn't know if more tests nees to be created, etc. That I could help with. Thanks @kazk

**Comment by kazk** [comment]
More tests will be nice. For example, I don't see any tests for when runtime error occurs.
I usually write much more tests when adding a language, see [lua_spec.js](https://github.com/Codewars/codewars-runner-cli/blob/90e681d98b6aa5eab1a41a647055978a88d17990/test/runners/lua_spec.js) and [go_spec.js](https://github.com/Codewars/codewars-runner-cli/blob/90e681d98b6aa5eab1a41a647055978a88d17990/test/runners/go_spec.js), but we don't have any requirements (maybe we should).

**Comment by jhoffner** [comment]
Power shell is now deployed and available as a Kumite. Error output is actually buggy and needs to be fixed before it can be promoted into being a kata language.

**Comment by BatmanAMA** [comment]
Where is this on being implemented for kata's? Is there anything I can do to help getting this there? Also, it looks like Kumite's could use an upgrade to [PowerShell Core RC](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-rc)

**Comment by kazk** [comment]
We're working on a new system and have PowerShell 6.0.0-beta.9 there. We can't give dates like when that will be available on Codewars yet.
I'll look into RC, thanks for the info.

**Comment by kenmaglio** [comment]
I was honestly would wait, January 20th PowerShell Core 6 should be released as GA.

**Comment by kazk** [comment]
Update: Added PowerShell Core 6 to the new system. See #562 for future updates/discussions.

**Pull request merged**
