### PR TITLE
Upgrade to Go 1.8

### PR DESCRIPTION
**Pull request by kazk**
Upgrade to [Go 1.8](https://golang.org/doc/go1.8) as planned. Simply replacing 1.7.5 with 1.8 should be [fine](https://golang.org/doc/go1compat).

### CODE REVIEW

**Comment by jhoffner** [comment]
Thanks! Hey you don't happen to know PHP do you? the Php image is failing on phpunit and I'm not sure what changed to break it.

**Comment by kazk** [comment]
I don't know PHP, but I can try? What do you mean by "failing on phpunit"?

**Comment by kazk** [comment]
I noticed that Go and Lua is still installed on `alt.docker`. I should remove those right? I can try looking into PHP while doing that.

**Comment by kazk** [comment]
Did this happen before?

```
Step 3/19 : RUN add-apt-repository ppa:ondrej/php
 ---> Running in d1a947b34295
 Co-installable PHP versions: PHP 5.6, PHP 7.0, PHP 7.1 and most requested extensions are included.

PLEASE DON'T USE PHP 5.4 OR PHP 5.5. The PHP 5.5 and later are no longer supported with security updates, therefore they are not included in this repository.

You can get more information about the packages at https://deb.sury.org

BUGS&FEATURES: This PPA now has a issue tracker: https://deb.sury.org/#bug-reporting

PLEASE READ: If you like my work and want to give me a little motivation, please consider donating regularly: https://donate.sury.org/

WARNING: add-apt-repository is broken with non-UTF-8 locales, see https://github.com/oerdnj/deb.sury.org/issues/56 for workaround:

# LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
 More info: https://launchpad.net/~ondrej/+archive/ubuntu/php
gpg: keyring `/tmp/tmpkgsk7hf3/secring.gpg' created
gpg: keyring `/tmp/tmpkgsk7hf3/pubring.gpg' created
gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpkgsk7hf3/trustdb.gpg: trustdb created
gpg: key E5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur�" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 687, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 370, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 261, in add_ppa_signing_key
    tmp_export_keyring, signing_key_fingerprint, tmp_keyring_dir):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 210, in _verify_fingerprint
    got_fingerprints = self._get_fingerprints(keyring, keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 202, in _get_fingerprints
    output = subprocess.check_output(cmd, universal_newlines=True)
  File "/usr/lib/python3.4/subprocess.py", line 609, in check_output
    output, unused_err = process.communicate(inputdata, timeout=timeout)
  File "/usr/lib/python3.4/subprocess.py", line 947, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 92: ordinal not in range(128)

 ---> d0bf7332f3c9
Removing intermediate container d1a947b34295
Step 4/19 : RUN sudo apt-get update
 ---> Running in 45330823ca04
```

**Comment by kazk** [comment]
I just built `alt-runner` after removing Go and Lua.

Maybe something went wrong while installing `phpunit`. The error message looks like `CodewarsListener.php` doesn't know about `PHPUnit_Util_Printer`.

```
PHP Fatal error:  Class 'PHPUnit_Util_Printer' not found in input on line 4
```

```
<?php
    use PHPUnit\Framework\TestCase;

    class CodewarsListener extends PHPUnit_Util_Printer implements PHPUnit_Framework_TestListener
```

**Comment by jhoffner** [comment]
Yeah those other languages can be removed. The PHP Fatal error error you are getting is the same as me. Did you rebuid your base image? that has changed, but if you haven't rebuilt than I can rule that out (i already rebuilt mine so couldn't test). 

I didn't notice the other error but possibly.

**Comment by kazk** [comment]
No, I didn't rebuild the base image.
I'll skip the tests and build `alt-runner`, then bash in to see what's going on. I'll let you know if I find anything.

**Comment by jhoffner** [comment]
thanks! that will help me out a lot.

**Comment by kazk** [comment]
When was the last successful `alt-runner` build?
I think `phpunit 5.7` was used before and it broke because `phpunit 6.0.8` is used now.

> PHPUnit 6.0 is the current stable release series.
It became stable on February 3, 2017.
Support for PHPUnit 6 ends February 8, 2019.
> <https://phpunit.de/>

```dockerfile
# I think this gets the latest stable release :(
RUN curl -OL https://phar.phpunit.de/phpunit.phar \
	&& chmod 755 phpunit.phar \
	&& mv phpunit.phar /usr/local/bin/ \
	&& ln -s /usr/local/bin/phpunit.phar /usr/local/bin/phpunit
```

I'll try using `"https://phar.phpunit.de/phpunit-5.7.phar"` and see if that fixes.

---

```
codewarrior@c785cdf84694:/runner$ which php
/usr/bin/php

codewarrior@c785cdf84694:/runner$ php -v
PHP 7.0.16-4+deb.sury.org~trusty+1 (cli) (built: Mar  2 2017 13:27:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16-4+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies

codewarrior@c785cdf84694:/runner$ which phpunit
/usr/local/bin/phpunit

codewarrior@c785cdf84694:/runner$ phpunit --version
PHPUnit 6.0.8 by Sebastian Bergmann and contributors.

codewarrior@c785cdf84694:/runner$ cat /home/codewarrior/run.php
<?php
  use phpunit\framework\TestCase;
  function add($a, $b) { return $a + $b; }
  class AddFunction extends TestCase {
    public function testAdd() {
      $this->assertEquals(add(1,1), 1);
    }
  }
?>
codewarrior@c785cdf84694:/runner$ phpunit --configuration=frameworks/php/phpunit/phpunit.xml /home/codewarrior/run.php
PHP Fatal error:  Class 'PHPUnit_Util_Printer' not found in /runner/frameworks/php/phpunit/CodewarsListener.php on line 4
```

**Comment by kazk** [comment]
@jhoffner the issue was caused by downloading latest stable release. Fixed by specifying phpunit 5.7.

**Comment by jhoffner** [comment]
Awesome! Thanks now we are one step closer to pushing all of these latest changes out.

**Comment by kazk** [comment]
Is there a reason to do `ADD . /runner` instead of selecting depending on the use? I think we should add more entries to `.dockerignore`. Wouldn't `.git/` cause needless cache invalidations?

```
codewarrior@c785cdf84694:/runner$ ls -al
total 196
drwxr-xr-x  1 root root  4096 Mar  8 19:20 .
drwxr-xr-x  1 root root  4096 Mar  8 19:21 ..
-rw-r--r--  1 root root  8196 Feb 24 23:56 .DS_Store
-rw-rw-r--  1 root root   230 Jan 18 01:42 .dockerignore
-rw-r--r--  1 root root   147 Mar  7 19:13 .editorconfig
drwxrwxr-x  8 root root  4096 Mar  8 19:20 .git
-rw-rw-r--  1 root root   296 Jan 18 01:42 .gitignore
-rw-rw-r--  1 root root   138 Jan 18 01:42 .travis.yml
-rw-rw-r--  1 root root  1313 Mar  8 19:20 Dockerfile
-rw-rw-r--  1 root root 34519 Jan 18 01:42 LICENSE
-rw-r--r--  1 root root  2290 Mar  8 18:37 Makefile
-rw-r--r--  1 root root 21125 Mar  7 19:13 README.md
drwxrwxr-x  2 root root  4096 Mar  8 18:38 docker
-rw-r--r--  1 root root 16206 Mar  7 19:13 docker-compose.yml
drwxrwxr-x  3 root root  4096 Mar  7 19:13 documentation
drwxrwxr-x  2 root root  4096 Mar  7 19:24 examples
drwxrwxr-x 20 root root  4096 Feb 28 22:36 frameworks
drwxrwxr-x  4 root root  4096 Jan 18 22:44 jvm-runner
drwxrwxr-x  3 root root  4096 Mar  7 22:40 lib
-rw-rw-r--  1 root root   578 Jan 18 01:42 listen.js
drwxr-xr-x  1 root root  4096 Mar  8 19:20 node_modules
-rw-rw-r--  1 root root  4220 Jan 18 01:42 package.json
-rw-rw-r--  1 root root    58 Jan 18 01:42 run-json.js
-rw-rw-r--  1 root root  2269 Jan 18 01:42 run.js
drwxrwxr-x  2 root root  4096 Jan 18 01:42 sample_data
drwxrwxr-x  3 root root  4096 Jan 18 22:44 test
-rw-rw-r--  1 root root   875 Jan 18 01:42 test_cs.sh
-rw-rw-r--  1 root root    76 Jan 18 01:42 tsconfig.json
drwxrwxr-x  4 root root  4096 Jan 18 22:44 typings
-rw-rw-r--  1 root root   599 Jan 18 01:42 typings.json
```

**Comment by jhoffner** [comment]
Mostly because of simplicity. Though I'm open to start being selective. The runner is starting to grow to a decent size. 

Dockerignore could probably use some work. Didn't realize .git was being added. We could also possibly maintain a separate docker ignore file for each image and copy that the same way the make copies the dockerfile.

**Comment by kazk** [comment]
> The runner is starting to grow to a decent size.

This is one of the reasons I proposed *micro* app for paradigm shift. I took some notes on the "Compressed Size" under "Tags" on Docker Hub.

- codewars/erlang-runner: 389 MB
- codewars/julia-runner: 399 MB
- codewars/func-runner: 474 MB
- codewars/base-runner: 527 MB
- codewars/dart-runner: 597 MB
- codewars/crystal-runner: 611 MB
- codewars/rust-runner: 687 MB
- codewars/systems-runner: 693 MB
- codewars/haskell-runner: 726 MB
- codewars/dotnet-runner: 732 MB
- codewars/ruby-runner: 782 MB
- codewars/alt-runner: 790 MB
- codewars/python-runner: 813 MB
- codewars/ocaml-runner: 833 MB
- codewars/node-runner: 885 MB
- codewars/jvm-runner: 1 GB
- codewars/swift-runner: 3 GB

---

> We could also possibly maintain a separate docker ignore file for each image and copy that the same way the make copies the dockerfile.

For this approach, whitelisting may work (ignore all `*` and `!pattern`).

**Pull request merged**
