### PR TITLE
added additional node packages

### PR DESCRIPTION
**Pull request by jhoffner**
- ramda
- packages to allow testing for css/stylus/less
- math
- axios (with mocking)
- A few unity related packages
- vuejs
- jquery

### CODE REVIEW

**Comment by kazk** [comment]
Can you look into updating [chai@1.9.2](http://chaijs.com/releases/#1.9.2) (`2014-09-29`)? (#299)

```
npm ERR! peer dep missing: chai@>= 2.1.2 < 4, required by chai-as-promised@5.3.0
npm ERR! peer dep missing: chai@>=2.1.2 <4, required by chai-deep-match@1.0.2
npm ERR! peer dep missing: chai@>=2.0.0 <4.0.0, required by chai-eventemitter@1.1.1
npm ERR! peer dep missing: chai@>= 2.1.2 < 4, required by chai-rx@0.0.2
```

Also, can we make `NPM_CONFIG_LOGLEVEL` to `warn`? `info` prints too much and it's hard to find issues.

**Comment by kazk** [comment]
[L9956](https://travis-ci.org/Codewars/codewars-runner-cli/builds/220390241#L9956)

```
npm ERR! shasum check failed for /tmp/npm-93-53189365/registry.npmjs.org/moment-timezone/-/moment-timezone-0.5.13.tgz
```

[L9951-9968](https://travis-ci.org/Codewars/codewars-runner-cli/builds/220390241#L9951)

```
npm ERR! Linux 3.19.0-66-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--only=dev"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! shasum check failed for /tmp/npm-93-53189365/registry.npmjs.org/moment-timezone/-/moment-timezone-0.5.13.tgz
npm ERR! Expected: 99ce5c7d827262eb0f1f702044177f60745d7b90
npm ERR! Actual:   cf50dd819cf32c3b508c0dd0673ad2f7be8e3f6a
npm ERR! From:     https://registry.npmjs.org/moment-timezone/-/moment-timezone-0.5.13.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by kazk** [comment]
@jhoffner can you close #373 and #296? I don't have enough permission here.

**Comment by jhoffner** [comment]
Done and done

**Pull request merged**
