### PR TITLE
[WIP][RFC] Adding D

### PR DESCRIPTION
**Pull request by kazk**
Adding [D](http://dlang.org/) with DMD 2.073.2.

Need some feedback from D users for test integration, see the comment below.

Any feedback is appreciated. 

---

- [x] Compile and run
- [ ] Test integration

---

#130, Codewars/codewars.com#654

### CODE REVIEW

**Comment by kazk** [comment]
Need some help looking into test integration. D has unit tests included in the language, but I haven't been able to find a way to take advantage of that.

---

Packages for testing from [DUB](https://code.dlang.org/search?q=test). Dates are `pushed_at` from GitHub API.

<dl>
<dt><a href="https://github.com/atilaneves/unit-threaded">atilaneves/unit-threaded</a></dt><dd>Advanced unit test framework for D (includes unittest blocks) (<em>2017-03-16</em>)</dd>

<dt><a href="https://github.com/nomad-software/dunit">nomad-software/dunit</a></dt><dd>Advanced unit testing toolkit for the D programming language (<em>2016-10-20</em>)</dd>

<dt><a href="https://github.com/linkrope/dunit">linkrope/dunit</a></dt><dd>xUnit Testing Framework for D (<em>2017-03-15</em>)</dd>

<dt><a href="https://github.com/jostly/specd">jostly/specd</a></dt><dd>Library for writing unit tests as specifications in D. (<em>2014-11-18</em>)</dd>

<dt><a href="https://github.com/rejectedsoftware/tested">rejectedsoftware/tested</a></dt><dd>Unit test runner with structured JSON output of results and resource usage (<em>2016-02-15</em>)</dd>

<dt><a href="https://github.com/yamadapc/bed">yamadapc/bed</a></dt><dd>bed is a work-in-progress BDD testing framework for D (<em>2016-04-01</em>)</dd>

<dt><a href="https://github.com/Straivers/Chap">Straivers/Chap</a></dt><dd>A D assertions library (<em>2017-01-26</em>)</dd>

<dt><a href="https://github.com/MartinNowak/qcheck">MartinNowak/qcheck</a></dt><dd>QuickCheck like test library (<em>2015-09-13</em>)</dd>

<dt><a href="https://github.com/dmonagle/feature-test-d">dmonagle/feature-test-d</a></dt><dd>A feature test framework for D applications or libraries that builds on unittest and does not need any external tools. (<em>2016-06-28</em>)</dd>
</dl>

**Comment by ConnorVG** [comment]
It makes little to no sense to utilise a testing framework when we could use the built in unittest functionality (especially when it comes to upgrading D versions and ending up with regression due to framework update delays).

There is some good documentation on it [here](https://dlang.org/spec/unittest.html).

**Comment by kazk** [comment]
@ConnorVG

I did try to make use of the builtin unittest.

> Need some help looking into test integration. D has unit tests included in the language, but I haven't been able to find a way to take advantage of that.

Can you show me how to customize the output of the builtin unittest? Or where I can find the information?

**Comment by ConnorVG** [comment]
Ah, customising the output might be a bit of a shitshow.

It's more of a:
 - did we choose to run unittests alongside the application?
 - ok; if a tests fails then just bail.

I get your point now, apologies.

**Comment by kazk** [comment]
No worries. Thanks for commenting. I was starting to think no one was interested :(

Do you know which is the most popular one?
`unittest` block was good enough for me when I used to play with D few years ago.

**Comment by ConnorVG** [comment]
I've never went all out with a framework, that's the problem. All of my needs have been happily tested with well-qualified `unittest` blocks. We may need a few people to give some input on this.

Pinging @Vercas

**Comment by kazk** [comment]
I noticed that Rust runner doesn't use any test framework (tested using `test` attribute) and transforms the final output into Codewars format.
I checked if that approach is possible for D.

```d
int add(int x, int y) { return x - y; } // fail
unittest {
  assert(add(1, 1) == 2);
}
void main() {}
```

This outputs the following to `stderr`:

```
core.exception.AssertError@code.d(3): unittest failure
----------------
??:? _d_unittest [0x427f9c]
??:? void code.__unittest_fail(int) [0x427e1e]
??:? void code.__unittestL2_1() [0x427d87]
??:? void code.__modtest() [0x427da0]
??:? int core.runtime.runModuleUnitTests().__foreachbody2(object.ModuleInfo*) [0x42a7bc]
??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)).__lambda2(immutable(object.ModuleInfo*)) [0x430ee2]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))).__foreachbody2(ref rt.sections_elf_shared.DSO) [0x43cc69]
??:? int rt.sections_elf_shared.DSO.opApply(scope int delegate(ref rt.sections_elf_shared.DSO)) [0x42e4a8]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))) [0x43cbf5]
??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)) [0x430eb9]
??:? runModuleUnitTests [0x42a69c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x4282ea]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x428283]
??:? _d_run_main [0x4281ef]
??:? main [0x427e37]
??:? __libc_start_main [0x9008df44]
```

The message `unittest failure` is the default and can be changed by passing optional message to `assert`.
I couldn't find a way to produce useful feedback :(

**Comment by kazk** [comment]
I'm going to look into using [trial](https://gitlab.com/szabobogdan3/trial) with [fluent-asserts](https://github.com/gedaiu/fluent-asserts).

**Pull request closed without merging**
