### PR TITLE
Fix UnitKit with setup code

### PR DESCRIPTION
**Pull request by kazk**
Make `solution.m` to only contain `opts.solution` and let `fixture.m` handle importing `setup.m`.

Resolves https://github.com/Codewars/codewars.com/issues/1221

### CODE REVIEW

**Comment by kazk** [comment]
@DonaldKellett This fixes the issue you reported, but I'm not sure if this is correct approach.

Generated `fixture.m` will look something like this:
```objc
#import "setup.m"
#import "solution.m"

#import <Foundation/Foundation.h>
#import <UnitKit/UnitKit.h>
@interface TestSuite : NSObject <UKTest>
@end

@implementation TestSuite
- (void)testNULL
{
  UKStringsEqual(@"", stringify(NULL));
}
- (void)testSingle
{
  UKStringsEqual(@"1", stringify([Node nodeWithData: 1]));
}
@end
```

Also, apparently `TestSuite` cannot be changed because `@interface TestSuite : NSObject <UKTest>` is included automatically. I'm not sure why this was written like this.

**Comment by DonaldKellett** [comment]
@kazk Many thanks for the fix, it looks fine to me by eye (but what do I know? :wink: ); feel free to ping me when this fix is deployed (to `preview` or otherwise) and I will be more than happy to test it out :smile:

**Comment by kazk** [comment]
I guess it doesn't look right to me because `solution.m` doesn't have import statement for `Node` (like `import "setup.h"`), but this is because of the way objc-runner is setup so I think it's unavoidable unfortunately.

> Also, apparently `TestSuite` cannot be changed because `@interface TestSuite : NSObject <UKTest>` is included automatically. I'm not sure why this was written like this.

This is because `TestSuite` is hardcoded here:
https://github.com/Codewars/codewars-runner-cli/blob/dbf943d62c8d6ed451d27ac1817c0f13b1de558c/lib/runners/objc.js#L158-L166

----

I think this is the best I can do without changing how the runner works.

**Comment by DonaldKellett** [comment]
Bump.

@kazk Would it be possible to merge this PR into the Codewars Runner CLI within the next few days if the changes mentioned above do not cause any new issues?  Or would this have to wait until the new CLI Runner licensing is sorted out?  Would love to see this Issue fixed as then I've got quite a few ObjC translations involving preloaded linked list / binary tree classes planned off the top of my head, cheers :smile:

**Comment by kazk** [comment]
@DonaldKellett 

> Would it be possible to merge this PR into the Codewars Runner CLI within the next few days if the changes mentioned above do not cause any new issues?

I don't think this will be merged within few days because Jake is out of office. I don't do merges and deployments for this one.

> Or would this have to wait until the new CLI Runner licensing is sorted out?

I'm not sure what you mean by licensing, but this fix is in the new one already.

**Comment by DonaldKellett** [comment]
> I don't think this will be merged within few days because Jake is out of office. I don't do merges and deployments for this one.

So I assume this PR can be merged once Jake is back in office?

> I'm not sure what you mean by licensing

You mentioned earlier that the restructuring of the Codewars CLI Runner was already mostly complete mid-November but CW is sorting out some legal issues with the new licensing?  I only asked this because I assumed that before that was sorted out, all changes to this Repo were on-hold.  But according to your reply in the previous paragraph, that doesn't seem to affect this PR which is good to know, cheers 😄

**Comment by kazk** [comment]
> So I assume this PR can be merged once Jake is back in office?

Can't promise, but this should get merged when he's back and have the time to deploy.

---

> You mentioned earlier that the restructuring of the Codewars CLI Runner was already mostly complete mid-November but CW is sorting out some legal issues with the new licensing?

Maybe you misunderstood my [comment](https://github.com/Codewars/codewars-runner-cli/issues/553#issuecomment-352083422)

> We also have to decide which parts to open source and how to accept contributions.

this is not about licensing.

---

> I only asked this because I assumed that before that was sorted out, all changes to this Repo were on-hold.

This repo is basically frozen. So no new features, only bug fixes and quick enhancements.

**Pull request merged**
