### PR TITLE
Enabled Typescript in Karma & Angular 2

### PR DESCRIPTION
**Pull request by OverZealous**
- TypeScript can now be run using `karma_tdd` and `karma_bdd` with Mocha
- Angular 4 can be tested (with quite a bit of imported code)
- Split out some of the Karma logic so it can be reused in the TS runner. Since it's still highly specialized, I didn't move it to a shared module yet.
- Upgraded Angular 1.5 and added Angular 1.6 to the mix for now
- Increased the default timeout for running TS tests (it takes at least 6-7 seconds to run Typescript+Karma)

### CODE REVIEW

**Comment by jhoffner** [comment]
@OverZealous looks good. My only main concern is will TypeScript 2 be compatible with all of our 1.8 Codewars content. It would be nice to be able to support both versions but thats probably going to require working with versions outside of NPM.

**Comment by OverZealous** [comment]
Uh, we've got 2.x installed. If you run the runner directly, and do `tsc --version`, it's 2.4

**Comment by OverZealous** [comment]
This is because we don't include versions when installing our global modules.

**Comment by OverZealous** [comment]
That being said, right now we can sort-of support a different one for Karma, because the Typescript used in Karma is not the same as the globally installed one.

**Comment by jhoffner** [comment]
Yeah no, I totally believe you that 2.4 is installed. I'm saying that since 1.8 is no longer installed, I hope the content will be compatible. Maybe I'm not understanding. 

@kazk this is a good example of where your versioned docker/directory structure would come in handy.

**Comment by kazk** [comment]
I described this concern in https://github.com/Codewars/codewars-runner-cli/issues/418.

**Comment by OverZealous** [comment]
I'm pretty sure the public one right now is running 2.4, simply because we run `npm install -g typescript` in the Docker image, without specifying the version.

I could be wrong, but the local copy within our `node_modules` directory was 1.x (due to being included with `typings`), and it threw an error on all of the existing (unchanged) files within `runner/typings`.

**Comment by jhoffner** [comment]
> I described this concern in #418.

> I'm pretty sure the public one right now is running 2.4, simply because we run npm install -g typescript in the Docker image

ah right I forgot. OK well in that case, at least we don't need to be worried about existing content since it hasn't been a major problem yet (or is it? I'm still not fully up-to-date on the issues backlog). 

We should probably target the locally installed typescript executable though so that we can lock versions to at least 2.x.

**Comment by OverZealous** [comment]
Yeah, I can do that, I'll set it to `@^2.4` for this PR, that's a good idea.

Technically we need to upgrade `typings`, too, but it had major breaking changes (including renaming `ambient` to `global`, and I could barely get through this update without breaking something. 😝

**Comment by kazk** [comment]
> this is a good example of where your versioned docker/directory structure would come in handy.

Yeah, images tagged with language version reduces a lot of pain.

Also is the typing compatible? (#380)

**Comment by OverZealous** [comment]
I didn't touch the typings here. I would not be surprised if they were way out of date. We really should be installing them correctly, but TypeScript isn't really my area, and I really had a lot of trouble hacking this work together.

**Comment by OverZealous** [comment]
OK, just to be 100% sure, I ran a test on our active runners, it's definitely been 2.4.1 for a while.

**Comment by OverZealous** [comment]
Ugh, the `object-curly-spacing` rule is lame. I can't see `{foo: 1, bar:2}` being better than `{ foo: 1, bar: 2 }`

**Comment by kazk** [comment]
What is `/typings` in the project root?

I don't know TypeScript much either, but I have something like this:
```dockerfile
RUN npm install -g typescript@^2.4.x @types/node@^8.0.x
```

TypeScript compiled to JavaScript and executed.
```sh
tsc --target ES2017 \
    --module commonjs \
    --typeRoots /usr/local/lib/node_modules/@types \
    $ts-file

node $js-file
```

This way `/// <reference path="/runner/typings/node/index.d.ts" />` is no longer necessary.
I don't know about the compatibility.

**Comment by jhoffner** [comment]
> Why is /typings in the project root?

This was a while ago and I forgot the specifics, but it might have something to do with NPM issues - and being related to why I needed to install using package.json instead of just using `npm install` commands directly within the Dockerfile. 

I think I might have struggled to get the paths to be clean as well. I didn't want users to have to know some cryptic path in order to find the reference, so I added them to the root.

**Comment by kazk** [comment]
I'm getting really confused.
[`typings`](https://www.npmjs.com/package/typings) is "The TypeScript Definition Manager."?
How is this used? I don't see `typings install` in the Dockerfile.

**Comment by jhoffner** [comment]
I think the typings were generated outside of Docker, due to NPM issues with generating them. I dont know if NPM still has Docker problems but back then it was extremely flimsy inside of Docker. 

So I generated them outside of the docker build process, which was a copout, and the reason why they have become so outdated. I see that I still install typings globally within the image, so I may have left that behind accidentally. I think I might be misremembering something as well - maybe NPM wasn't part of the issue IDK - but I remember this being a total PITA for some kind of reason. Unfortunately I didn't document the issues properly.

Either way, it's a hack and needs to be handled. We can handle that as a separate PR though.

**Comment by kazk** [comment]
Ok, that makes sense. `npm install -gq typings` confused me.
I haven't experienced npm issues so it might have resolved since you experienced it.
Caching might have been painful since you do `ADD . /runner`?
The size of images can be easily reduced by removing `/tmp/node_modules` after copying to `/runner/node_modules` or just move instead.
Depending on your Docker version, you can also do multi-stage build which caches images separately so you don't have to do the hack to begin with.

**Pull request merged**
