### PR TITLE
Add Nim

### LINKED ISSUE #177: Add support for Nim
Could you guys add the Nim programming language as a future Language implementation? http://nim-lang.org

### PR DESCRIPTION
**Pull request by kazk**
Adding [Nim](https://nim-lang.org/) :crown:

Any feedback is appreciated.

---

- [x] Compile and run
- [x] Test integration
- [x] Documentation
- [x] Packages. Not in this PR. Look into `nimble`. Need feedback.
- [x] Specify Nim's version: v0.17.0.
- [x] Compile separately? Maybe in the future. (remove `--run` and execute built `./fixture`)
- [x] Look into improving stack trace. Good enough for now.

---

Closes #177

### CODE REVIEW

**Comment by jhoffner** [comment]
Its niche but I know a number of people who will be super happy to have Nim support!

**Comment by kazk** [comment]
That's nice to know :) I'd definitely need some help from them because I'll be learning Nim as I work on this. I knew the name Nimrod/Nim, but never tried.

I'm going to work on this openly to get feedbacks and have a TODO list instead of splitting into smaller PRs for convenience. I'll also try to organize commits by features so that it's easier for others to continue the work if I get stuck.

**Comment by kazk** [comment]
The included [`unittest`](https://nim-lang.org/docs/unittest.html) was relatively easy to modify even without Nim knowledge.

```nim
# solution.nim
proc add*(x, y: int): int =
  return x + y
```

```nim
# fixture.nim
import unittest
import solution

suite "add":
  test "1 + 1 = 2":
    check(add(1, 1) == 2)
```

```
<DESCRIBE::>add
<IT::>1 + 1 = 2
<PASSED::>Test Passed
<COMPLETEDIN::>
<COMPLETEDIN::>
```

**Comment by kazk** [comment]
Looks like support for custom test report formatter was merged to `devel` branch yesterday 🎉  
This should allow us to use the standard `unittest` by defining `CodewarsOutputFormatter`. I'll start looking into this.

**Comment by kazk** [comment]
@jhoffner

This is mostly complete. There're some things that bothers me, but my Nim knowledge is limited and I don't think I can improve this further.
- Failure message is not great
- `addOutputFormatter(OutputFormatter(newCodewarsOutputFormatter()))` in `opts.fixture`

**Comment by jhoffner** [comment]
@kazk I'm tempted to try rebase and merge and see what happens here...

**Comment by kazk** [comment]
What do you mean? I'll clean up the commits if that's what you mean.

**Comment by jhoffner** [comment]
We have been using the Squash and merge feature and just decided that its not working well for us. However we have not leveraged Github's Rebase and merge feature. I'm curious if Github will use `git rebase --interactive` and if so, if the squashed commit will be packed up for us and also not confuse history for later PR's. 

However rebasing is a destructive operation and I usually stay away from it because of the possible issues it can cause so I'm hesitant to experiment with how well Github's feature will do this for us. I've seen the "Rebase and merge" option disabled before, so I'm assuming Github tries to detect if any issues will emerge from doing so and prevent the rebase in those cases.

**Comment by kazk** [comment]
Ok, I haven't read their documentation much. I wouldn't mind you trying it :)

**Comment by jhoffner** [comment]
OK, no interactive merge unfortunately, but at least the commit history is in order.

BTW I'm not sure when I will deploy this, I may have to hold off til next sprint (August). I'm working on CR performance issues and don't want to add more variables to the effort at the moment.

**Comment by kazk** [comment]
Looks like we should just go back to plain merge. I like how git allows one to work concurrently and changing history makes things complicated. I like graphs like this :]
image

For deploying Nim, I understand. Let me know whenever it becomes available on preview so I can test it further.

**Pull request merged**
