### PR TITLE
C++ Support

### PR DESCRIPTION
**Pull request by Dan-Nolan**
- Adds C++ support with Igloo BDD testing
- Fixes C# issue [Codewars #5](https://github.com/Codewars/codewars.com/issues/5)

### CODE REVIEW

**Comment by Dan-Nolan** [comment]
Addresses https://github.com/Codewars/codewars-runner-cli/issues/10

**Comment by jhoffner** [comment]
Are we still missing the `<:LF:>` line break replacement token in this? Also what version of C++ is it running?

**Comment by Dan-Nolan** [comment]
Just added the `<LF::>`, and we're at C++ 14 :)

**Comment by jhoffner** [comment]
CI failures 
```
  10 passing (9s)
  2 failing

  1) cpp runner .run should handle basic code evaluation:

      Uncaught AssertionError: expected '' to equal '"Within C++, there is a much smaller and cleaner language struggling to get out." - Bjarn Stroustrup'
      + expected - actual

      +"Within C++, there is a much smaller and cleaner language struggling to get out." - Bjarn Stroustrup
      
      at test/runners/cpp_spec.js:14:42
      at lib/shovel.js:37:13
      at ChildProcess.<anonymous> (lib/shovel.js:178:9)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

  2) cpp runner .run igloo bdd should handle inheritance like a champ:
     Uncaught AssertionError: expected '' to include '<DESCRIBE::>inheritance_tests'
      at test/runners/cpp_spec.js:309:46
      at lib/shovel.js:37:13
      at ChildProcess.<anonymous> (lib/shovel.js:178:9)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by Dan-Nolan** [comment]
Not really sure how those two examples are related and it's working locally. I'll try rebuilding and seeing if I can reproduce it somehow...

**Comment by Dan-Nolan** [comment]
Turns out node process 'exit' occurs before all stdio streams are closed. Changing to the closed event fixed the issue.

**Comment by jhoffner** [comment]
👍 🎉 🍔

**Pull request merged**
