### PR TITLE
Add Lua support

### LINKED ISSUE #166: Support for Lua
Being one of the top voted languages for Codewars, I think it makes sense to take some time and integrate Lua inside Codewars. I'll let it be for the time being in order to finish first what I'd love to integrate (F#, VB,Kotlin & Go). If by the time no one pick this baby up, I will assign it to myself and work on it :+1:

### PR DESCRIPTION
**Pull request by kazk**
Add [Lua](http://www.lua.org/) support. Uses [busted](https://olivinelabs.com/busted).

This closes #166.

### CODE REVIEW

**Comment by jhoffner** [comment]
@kazk here is a list of lua packages that might make sense to add. https://github.com/LewisJEllis/awesome-lua

Not sure how many of those would make sense in CW's context but it would be cool if some of the game related packages were on there - so that more game specific kata could be created.

**Comment by kazk** [comment]
Thanks! I'll look into them.

---

I'm in the process of finally upgrading my OS, so I'll continue working on this PR once I'm done. I've been learning Docker and not having proper environment (Docker compose doesn't work, for example) became unbearable.

**Comment by kazk** [comment]
@jhoffner I decided to go with Lua 5.2 and not add any extra packages for now. This is mainly because I'm not familiar with Lua and had no idea.

Please let me know if you find any issues or questions.

**Comment by jhoffner** [comment]
This is deployed now to CW (along with all of the other recent updates).

**Comment by kazk** [comment]
Thanks for letting me know. I'll try translating "Two Oldest Ages".

---

I found one minor issue in "Test Cases" and "Example Test Cases".

image

Lua's line comment starts with `--`, so it should be:

```lua
-- TODO: Replace examples and use TDD development by writing your own tests
local solution = require 'solution'
describe("solution", function()
  it("test for something", function()
    assert.are.same("expected", solution.foo())
  end)
end)
```

**Comment by LPII** [comment]
Just dropped in to say thanks for this @kazk

**Comment by kazk** [comment]
@LPII :) Let me know if you find any issues.

I recently realized that I forgot to support "Preloaded" code so I'll fix that soon before I forget.

**Pull request merged**
