### PR TITLE
update elixir version to 1.5.1

### PR DESCRIPTION
**Pull request by jademcgough**
I tried to use `Enum.chunk_every/2` on a kata, only to realize that the version of Elixir that Codewars is running is nearly two years old.

The language is young and is changing fairly rapidly, so it would be great to update to Elixir 1.5.

### CODE REVIEW

**Comment by kazk** [comment]
See https://github.com/Codewars/codewars-runner-cli/issues/291#issuecomment-324186809

**Comment by jademcgough** [comment]
@kazk ah, thanks, guess I could have searched open issues more thoroughly.

Would my PR be sufficient to update the build version? If not, what would you want to see done? I'd be happy to contribute more to get this fixed.

**Comment by kazk** [comment]
Thanks for contributing.
Currently, the only way to add newer version is to install multiple versions and switch them depending on the given option. This is because we can only have single `elixir-runner` image and we need to keep the old versions for existing content. I mentioned [asdf](https://github.com/asdf-vm/asdf) as a possible workaround in the comment for this reason.

The current system has been painful to maintain and doesn't scale well, so we're designing a new one to eliminate this issue in general. We can't give an ETA yet.

**Comment by kazk** [comment]
Closing this because of the reasons I commented above.

The new system that supports multiple versions is coming. Most of the basic features are complete, but we're still working on it. I'm the only one working on it at the moment so it took a month or so to add 36 languages.

Adding a new language version will become as easy as creating a new Docker container image (e.g., `codewars/elixir:1.5`) and adjusting the way to execute if there's any incompatibility. Adjustments can be made without affecting other versions.

For Elixir, I rewrote to use `mix test` so we can enhance it in the future like adding some packages and support multiple files.

**Pull request closed without merging**
