### PR TITLE
Can you please try this?

### PR DESCRIPTION
**Pull request by javatlacati**
Can't test it since Groovy runner seems to be down :cry:

Tryed this on tutorialspoint site, sending a file with the fixture first and below the code.

### CODE REVIEW

**Comment by jhoffner** [comment]
Oh man. That JVM runner thing scares me (I don't code in Clojure). I'll see what I can do. I'm going to be looking into more CR stuff later on today hopefully.

**Comment by javatlacati** [comment]
Yes... but if you could make the JVM runner to run this clojure code you will have instantly groovy support :dancers: 

Even if thois doesn't run Groovy has it's own assert function so you just run two programs instead of one and again you can get easily the fixture capability :smiley_cat:

**Comment by jhoffner** [comment]
I'm not sure what is happening here. Did you check in a test case for functionality that you would like to be there but isn't, or for functionality that you believe to already be there but wasn't able to test?

**Comment by javatlacati** [comment]
Please check  issue #175. Since groovy runner seems to be down you can't test the code. Once fixed hopefully you'll be able to run the code from [This Kata](http://www.codewars.com/kumite/574f1554f4202c807000000f?sel=574f1554f4202c807000000f) if it passes then this PR should pass and you'll have a functional junit testing framework for groovy :sunglasses:

**Pull request closed without merging**
