### PR TITLE
Rewrite Swift runner

### LINKED ISSUE #448: Rewrite Swift runner using XCTestObservation
Swift runner is huge (#328) and takes forever to build (#422) because it's not following the best practices and compiling the entire Swift project from source.

This can be avoided by using the official builds, writing our own `XCTMain` and `CodewarsObserver` implementing [`XCTestObservation`](https://github.com/apple/swift-corelibs-xctest/blob/90ac02ae746c0776e7e37e4a00db7b38040d9116/Sources/XCTest/Public/XCTestObservation.swift) protocol.
Existing Kata should be able to migrate by replacing `XCTMain` with `_XCTMain`, but I'm not sure.

```swift
// `XCTMain` without filtering, using `CodewarsObserver`.
@_exported import Foundation
import XCTest
import Glibc

public func _XCTMain(_ testCases: [XCTestCaseEntry]) -> Never {
  XCTestObservationCenter.shared().addTestObserver(CodewarsObserver())
  let root = XCTestSuite(name: "All tests")
  let current = XCTestSuite(name: "\(Bundle.main.bundleURL.lastPathComponent).xctest")
  root.addTest(current)
  testCases.map(TestCaseSuite.init).forEach(current.addTest)
  root.run()
  exit(root.testRun!.totalFailureCount == 0 ? 0 : 1)
}

fileprivate class TestCaseSuite: XCTestSuite {
  // ...
}
```

```swift
import XCTest

public class CodewarsObserver: XCTestObservation {
  func testBundleWillStart(_ testBundle: Bundle) {}
  func testSuiteWillStart(_ testSuite: XCTestSuite) {}
  func testCaseWillStart(_ testCase: XCTestCase) {}
  func testCase(_ testCase: XCTestCase, didFailWithDescription description: String, inFile filePath: String?, atLine lineNumber: UInt) {}
  func testCaseDidFinish(_ testCase: XCTestCase) {}
  func testSuiteDidFinish(_ testSuite: XCTestSuite) {}
  func testBundleDidFinish(_ testBundle: Bundle) {}
}
```

```swift
// entry point
import XCTest

_XCTMain([testCase(T1.allTests), testCase(T2.allTests)])
```

```
<DESCRIBE::>T1
<IT::>test_foo
<PASSED::>Test Passed
<COMPLETEDIN::>0.000
<COMPLETEDIN::>0.000
<DESCRIBE::>T2
<IT::>test_bar
<PASSED::>Test Passed
<COMPLETEDIN::>0.000
<COMPLETEDIN::>0.000
```

### PR DESCRIPTION
**Pull request by kazk**
Rewrite swift runner using `XCTestObservation` protocol.
Test results are now reported through `CodewarsObserver` which is registered by `_XCTMain`.

This way, we no longer need to hack the source.

- Use Swift version 3.1.1, official build for Ubuntu 14.04
- Files are now compiled with `swiftc` and are no longer concatenated
  - This passes existing tests, but requires further testing
  - `solutionOnly`:
    - `opts.solution` is written to `main.swift`
    - `opts.setup` is compiled together if provided as `setup.swift`
  - `testIntegration`:
    - `opts.fixture` is written to `main.swift`
    - `opts.solution` is compiled together as `solution.swift`
    - `opts.setup` is compiled together if provided as `setup.swift`
- Make Travis build and test swift-runner
- Remove cw-2 test framework
- Update examples

The new image is less than 2 GB uncompressed.

image

Required Changes

- Use `_XCTMain` instead of `XCTMain`
- `import XCTest` is required

Output Compatibility

Outputs are mostly compatible with the original.
The failure messages are now reported with `<FAILED::>description` not `<FAILED::>Test Failed` followed by `<ERROR::>description`.
The output for test cases with multiple assertions changed. `IT` only contains single `PASSED`, `FAILED` or `ERROR`.

Closes #448

### CODE REVIEW

**Comment by OverZealous** [comment]
This is awesome! I love commits with way more lines removed than added!

**Comment by jhoffner** [comment]
This is great @kazk! Funny enough I was just troubleshooting Swift build issues on our new build server, so I'm eager to merge this in. 

It's a little bit of a bummer that we lost resolution on how many assertions passed within a failing spec, but it's not a big deal. Other languages work the same. Sometimes test creators get a little too happy with creating only 1 or 2 tests with far too many assertions within each, I'm not really sure how helpful it was to see the additional assertions (so that they at least see they are making progress on a spec). 

Beyond that though this looks like a huge improvement!

**Comment by kazk** [comment]
@jhoffner 

Is this valid?

```
<IT::>testWithMultiple
<PASSED::>Test Passed
<FAILED::>some test failed
<COMPLETED::>0.000
```

I can try to look into how it used to work if this is valid format.

**Comment by jhoffner** [comment]
Yes, that is valid.

**Comment by jhoffner** [comment]
@kazk I went ahead and merged since I am in the process of building out the new images and testing them. The multiple assertions tweaks can be a separate PR if you end up finding a solution.

**Comment by kazk** [comment]
I'll open another PR if I find a way to do this without messing with XCTest's source.

I think the original one had output like this for 1 passing and 1 failing (guessing from the tests):
```
<IT::>testWithMultiple
<PASSED::>Test Passed
<FAILED::>Test Failed
<ERROR::>failure description
<COMPLETED::>1
```

**Pull request merged**
